//
//  CameraViewController.swift
//  TravelBug
//
//  Created by Woodson, Tianna A (CTR) on 4/27/18.
//  Copyright © 2018 Tianna Woodson. All rights reserved.
//

import UIKit

class CameraViewController: UIViewController {

    //UI Elements
    @IBOutlet var captureButton: UIButton!
    @IBOutlet var photoModeButton: UIButton!
    @IBOutlet var toggleCameraButton: UIButton!
    @IBOutlet var toggleFlashButton: UIButton!
    @IBOutlet var videoModeButton: UIButton!
    
    
    //Instance variables
    let cameraController = CameraController()
    
    ///Displays a preview of the video output generated by the device's cameras.
    @IBOutlet var capturePreviewView: UIView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        func styleCaptureButton() {
            captureButton.layer.borderColor = UIColor.black.cgColor
            captureButton.layer.borderWidth = 2
            
            captureButton.layer.cornerRadius = min(captureButton.frame.width, captureButton.frame.height) / 2
        }
        func configureCameraController() {
            cameraController.prepare {(error) in
                if let error = error {
                    print(error)
                }
                
                try? self.cameraController.displayPreview(on: self.capturePreviewView)
            }
        }
        
        styleCaptureButton()
        configureCameraController()
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
}
